DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES (
product_id INT AUTO_INCREMENT  PRIMARY KEY,
brand_id INT NOT NULL,
start_date DATETIME NOT NULL,
end_date DATETIME NOT NULL
city_name VARCHAR(50) NOT NULL,
);